server:
  port: 8080 # gateway가 동작하는 port

  
spring:
  cloud:
    discovery:
      enabled: true
    gateway:
      routes:
      - id: user
        # 목적지
        uri: http://192.168.65.39:8080/
        predicates:
        - Path=/user/**
        - Method=Post
      - id: log
        # 목적지
        uri: http://192.168.65.39:8080/
        predicates:
        - Path=/log/**
        - Method=GET
      - id: metric
        # 목적지
        uri: http://192.168.65.39:8080/
        predicates:
        - Path=/metric/**
        - Method=GET
        
